export const contacts = [
  {
    id: 1,
    personName: "sandanu vitharana",
    email: "something@gmail.com",
    phone: "0757488372",
    favourite: true,
  },
  {
    id: 2,
    personName: "julios mendis",
    email: "mendis@gmail.com",
    phone: "0712345678",
    favourite: false,
  },
  {
    id: 3,
    personName: "john smith",
    email: "john.smith@gmail.com",
    phone: "0723456789",
    favourite: true,
  },
  {
    id: 4,
    personName: "emma wilson",
    email: "emma.wilson@gmail.com",
    phone: "0734567890",
    favourite: false,
  },
  {
    id: 5,
    personName: "michael brown",
    email: "michael.brown@gmail.com",
    phone: "0745678901",
    favourite: true,
  },
  {
    id: 6,
    personName: "sarah davis",
    email: "sarah.davis@gmail.com",
    phone: "0756789012",
    favourite: false,
  },
  {
    id: 7,
    personName: "james johnson",
    email: "james.johnson@gmail.com",
    phone: "0767890123",
    favourite: false,
  },
  {
    id: 8,
    personName: "olivia martin",
    email: "olivia.martin@gmail.com",
    phone: "0778901234",
    favourite: true,
  },
  {
    id: 9,
    personName: "david taylor",
    email: "david.taylor@gmail.com",
    phone: "0789012345",
    favourite: false,
  },
  {
    id: 10,
    personName: "sophia anderson",
    email: "sophia.anderson@gmail.com",
    phone: "0790123456",
    favourite: true,
  },
  {
    id: 11,
    personName: "alexander thomas",
    email: "alex.thomas@gmail.com",
    phone: "0701234567",
    favourite: false,
  },
  {
    id: 12,
    personName: "laura evans",
    email: "laura.evans@gmail.com",
    phone: "0700000012",
    favourite: true,
  },
  {
    id: 13,
    personName: "ryan clark",
    email: "ryan.clark@gmail.com",
    phone: "0700000013",
    favourite: false,
  },
  {
    id: 14,
    personName: "linda white",
    email: "linda.white@gmail.com",
    phone: "0700000014",
    favourite: true,
  },
  {
    id: 15,
    personName: "kevin hall",
    email: "kevin.hall@gmail.com",
    phone: "0700000015",
    favourite: false,
  },
  {
    id: 16,
    personName: "amy young",
    email: "amy.young@gmail.com",
    phone: "0700000016",
    favourite: true,
  },
  {
    id: 17,
    personName: "george king",
    email: "george.king@gmail.com",
    phone: "0700000017",
    favourite: false,
  },
  {
    id: 18,
    personName: "natalie scott",
    email: "natalie.scott@gmail.com",
    phone: "0700000018",
    favourite: true,
  },
  {
    id: 19,
    personName: "paul green",
    email: "paul.green@gmail.com",
    phone: "0700000019",
    favourite: false,
  },
  {
    id: 20,
    personName: "lauren adams",
    email: "lauren.adams@gmail.com",
    phone: "0700000020",
    favourite: true,
  },
  {
    id: 21,
    personName: "brandon moore",
    email: "brandon.moore@gmail.com",
    phone: "0700000021",
    favourite: false,
  },
  {
    id: 22,
    personName: "megan lee",
    email: "megan.lee@gmail.com",
    phone: "0700000022",
    favourite: true,
  },
  {
    id: 23,
    personName: "brian turner",
    email: "brian.turner@gmail.com",
    phone: "0700000023",
    favourite: false,
  },
  {
    id: 24,
    personName: "karen hill",
    email: "karen.hill@gmail.com",
    phone: "0700000024",
    favourite: true,
  },
  {
    id: 25,
    personName: "patrick allen",
    email: "patrick.allen@gmail.com",
    phone: "0700000025",
    favourite: false,
  },
  {
    id: 26,
    personName: "isabella ward",
    email: "isabella.ward@gmail.com",
    phone: "0700000026",
    favourite: true,
  },
  {
    id: 27,
    personName: "ethan baker",
    email: "ethan.baker@gmail.com",
    phone: "0700000027",
    favourite: false,
  },
  {
    id: 28,
    personName: "chloe cooper",
    email: "chloe.cooper@gmail.com",
    phone: "0700000028",
    favourite: true,
  },
  {
    id: 29,
    personName: "tyler parker",
    email: "tyler.parker@gmail.com",
    phone: "0700000029",
    favourite: false,
  },
  {
    id: 30,
    personName: "victoria ross",
    email: "victoria.ross@gmail.com",
    phone: "0700000030",
    favourite: true,
  },
  // {
  //   id: 31,
  //   personName: "noah bell",
  //   email: "noah.bell@gmail.com",
  //   phone: "0700000031",
  // },
  // {
  //   id: 32,
  //   personName: "grace foster",
  //   email: "grace.foster@gmail.com",
  //   phone: "0700000032",
  // },
  // {
  //   id: 33,
  //   personName: "logan rivera",
  //   email: "logan.rivera@gmail.com",
  //   phone: "0700000033",
  // },
  // {
  //   id: 34,
  //   personName: "zoe stevens",
  //   email: "zoe.stevens@gmail.com",
  //   phone: "0700000034",
  // },
  // {
  //   id: 35,
  //   personName: "aaron lawrence",
  //   email: "aaron.lawrence@gmail.com",
  //   phone: "0700000035",
  // },
  // {
  //   id: 36,
  //   personName: "ella morgan",
  //   email: "ella.morgan@gmail.com",
  //   phone: "0700000036",
  // },
  // {
  //   id: 37,
  //   personName: "samuel reed",
  //   email: "samuel.reed@gmail.com",
  //   phone: "0700000037",
  // },
  // {
  //   id: 38,
  //   personName: "mia price",
  //   email: "mia.price@gmail.com",
  //   phone: "0700000038",
  // },
  // {
  //   id: 39,
  //   personName: "oliver butler",
  //   email: "oliver.butler@gmail.com",
  //   phone: "0700000039",
  // },
  // {
  //   id: 40,
  //   personName: "hannah wright",
  //   email: "hannah.wright@gmail.com",
  //   phone: "0700000040",
  // },
  // {
  //   id: 41,
  //   personName: "leo hughes",
  //   email: "leo.hughes@gmail.com",
  //   phone: "0700000041",
  // },
  // {
  //   id: 42,
  //   personName: "nina walsh",
  //   email: "nina.walsh@gmail.com",
  //   phone: "0700000042",
  // },
  // {
  //   id: 43,
  //   personName: "omar ali",
  //   email: "omar.ali@gmail.com",
  //   phone: "0700000043",
  // },
  // {
  //   id: 44,
  //   personName: "claire henry",
  //   email: "claire.henry@gmail.com",
  //   phone: "0700000044",
  // },
  // {
  //   id: 45,
  //   personName: "felix diaz",
  //   email: "felix.diaz@gmail.com",
  //   phone: "0700000045",
  // },
  // {
  //   id: 46,
  //   personName: "pearl cole",
  //   email: "pearl.cole@gmail.com",
  //   phone: "0700000046",
  // },
  // {
  //   id: 47,
  //   personName: "adrian cruz",
  //   email: "adrian.cruz@gmail.com",
  //   phone: "0700000047",
  // },
  // {
  //   id: 48,
  //   personName: "rachel fox",
  //   email: "rachel.fox@gmail.com",
  //   phone: "0700000048",
  // },
  // {
  //   id: 49,
  //   personName: "marcus warren",
  //   email: "marcus.warren@gmail.com",
  //   phone: "0700000049",
  // },
  // {
  //   id: 50,
  //   personName: "sylvia perez",
  //   email: "sylvia.perez@gmail.com",
  //   phone: "0700000050",
  // },
  // {
  //   id: 51,
  //   personName: "derek mills",
  //   email: "derek.mills@gmail.com",
  //   phone: "0700000051",
  // },
  // {
  //   id: 52,
  //   personName: "linda cross",
  //   email: "linda.cross@gmail.com",
  //   phone: "0700000052",
  // },
  // {
  //   id: 53,
  //   personName: "kenneth griffin",
  //   email: "kenneth.griffin@gmail.com",
  //   phone: "0700000053",
  // },
  // {
  //   id: 54,
  //   personName: "ivy lawson",
  //   email: "ivy.lawson@gmail.com",
  //   phone: "0700000054",
  // },
  // {
  //   id: 55,
  //   personName: "ronald simmons",
  //   email: "ronald.simmons@gmail.com",
  //   phone: "0700000055",
  // },
  // {
  //   id: 56,
  //   personName: "vivian steele",
  //   email: "vivian.steele@gmail.com",
  //   phone: "0700000056",
  // },
  // {
  //   id: 57,
  //   personName: "edward hart",
  //   email: "edward.hart@gmail.com",
  //   phone: "0700000057",
  // },
  // {
  //   id: 58,
  //   personName: "nora fletcher",
  //   email: "nora.fletcher@gmail.com",
  //   phone: "0700000058",
  // },
  // {
  //   id: 59,
  //   personName: "colin simpson",
  //   email: "colin.simpson@gmail.com",
  //   phone: "0700000059",
  // },
  // {
  //   id: 60,
  //   personName: "bella hayes",
  //   email: "bella.hayes@gmail.com",
  //   phone: "0700000060",
  // },
];
